---
title: "Višina plač in dodatkov vodilnih uslužbencev v javnem sektorju v 2010 – 2014"
subtitle: "Pod črto"
author: ""
date: "`r Sys.Date()`"
output:
  tint::tintHtml: 
     self_contained: TRUE
     keep_md: true
#bibliography: skeleton.bib
link-citations: no
---

```{r setup, include=FALSE}
library(tint)
# invalidate cache when the package version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tint'))
options(htmltools.dir.version = FALSE)
source("../../functions/ggplot_tema.R")
load(file = "../data/Poslanske_place.RData")
library(tidyverse)
library(forcats)
library(tidyr)
library(plotly)
```

#

## Po skupini delovnega mesta

```{r "Po skupini delovnega mesta", message=F, echo=F, warning=F, fig.width = 12, fig.asp = 0.58, out.width="95%", fig.align='center'}
g.povprecna.placa.skupina
```

## Poslanci
```{r "Poslanci", message=F, echo=F, warning=F, fig.width = 12, fig.asp = 0.58, out.width="95%", fig.align='center'}
g.povprecna.placa.poslanci
```


### Malo drugače
```{r "Malo drugače", message=F, echo=F, warning=F, fig.width = 12, fig.asp = 0.58, out.width="95%", fig.align='center'}
g01.povprecna.placa.poslanci
```

## Dodatki
```{r "Dodatki", message=F, echo=F, warning=F, fig.width = 14, fig.asp = 0.58, out.width="95%", fig.align='center'}
g02.povprecna.izplacila.dodatkov
```


